In [2]:
import numpy as np
import matplotlib.pyplot as plt

Create a vector with values ranging from 10 to 49.

In [2]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a 3x3 matrix with values ranging from 0 to 8.

In [4]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix.


In [6]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a 3x3x3 array with random values.

In [7]:
d = np.random.random((3,3,3))
d

array([[[0.79739605, 0.12500869, 0.27780026],
        [0.04223905, 0.01002976, 0.9451664 ],
        [0.4114577 , 0.88764014, 0.96638625]],

       [[0.80226632, 0.94938793, 0.17398243],
        [0.58136345, 0.48357758, 0.81409323],
        [0.06062561, 0.02108277, 0.49226774]],

       [[0.21586403, 0.45831155, 0.96188864],
        [0.15984311, 0.82388817, 0.05059574],
        [0.48585262, 0.38659064, 0.22587601]]])

Create a 10x10 array with random values and find the minimum and maximum values.

In [9]:
e = np.random.random(100).reshape(10,10)
print(e.min(), e.max())

0.003927844415446025 0.9913666105018822


Create a random vector of size 30 and find the mean value.

In [10]:
f = np.random.random(30)
f.mean()

np.float64(0.42437651932664944)

Normalize a 5x5 random matrix.

In [37]:
g = np.random.random(25).reshape(5,5)
norm = np.linalg.norm(g)
normalized = g / norm
normalized


2.9557698833719974


array([[0.05887584, 0.19943694, 0.23926501, 0.335614  , 0.18071355],
       [0.30156096, 0.3257621 , 0.0960892 , 0.04789836, 0.2447386 ],
       [0.11008592, 0.23999749, 0.20473915, 0.2784803 , 0.01097026],
       [0.01174386, 0.17287325, 0.13030214, 0.08856686, 0.20517676],
       [0.14117977, 0.20283356, 0.23895316, 0.2551235 , 0.1273647 ]])

Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).


In [39]:
v1 = np.random.rand(5,3)
v2 = np.random.rand(3,2)
v1 @ v2

array([[0.69108842, 0.28527625],
       [0.75865474, 0.60928355],
       [0.87355796, 0.84669013],
       [0.57428604, 0.34493407],
       [0.51948938, 0.88342866]])

Create two 3x3 matrices and compute their dot product.


In [41]:
v3 = np.random.rand(3,3)
v4 = np.random.rand(3,3)
v3.dot(v4)

array([[0.5506381 , 0.94304955, 0.35723749],
       [0.62577634, 1.1365583 , 0.35247444],
       [0.25207022, 0.66337128, 0.16889787]])

Given a 4x4 matrix, find its transpose.


In [54]:
v5 = np.random.rand(4,4).astype(np.float64)
v5.transpose()

array([[0.84242828, 0.17875252, 0.08649345, 0.55016235],
       [0.38916427, 0.70290301, 0.90705719, 0.35806199],
       [0.79233292, 0.40299156, 0.14545606, 0.03038034],
       [0.3055409 , 0.67002202, 0.73846553, 0.46035023]])

Create a 3x3 matrix and calculate its determinant.


In [55]:
v6 = np.random.rand(3,3)
np.linalg.det(v6)

np.float64(0.19493452263950065)

Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).

In [3]:
A = np.random.rand(3,4).astype(np.int64)
B = np.random.rand(4,3).astype(np.int64)

ans = np.dot(A,B)
ans

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.

In [5]:
v10 = np.random.rand(3,3).astype(np.int64)
v11 = np.random.rand(3,1).astype(np.int64)
print(np.dot(v10,v11))

[[0]
 [0]
 [0]]


Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.


In [7]:
v12 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

v13 = np.array([1,2,3])

if np.linalg.det(v12) != 0:
    x = np.linalg.solve(v12,v13)
    print(x)
else:
    print("No solution")

No solution


Given a 5x5 matrix, find the row-wise and column-wise sums

In [3]:
matrix = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])

row = np.sum(matrix, axis=1)

column = np.sum(matrix, axis=0)

print(row)
print(column)

[ 15  40  65  90 115]
[55 60 65 70 75]
