In [1]:
import numpy as np

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
type(a)

numpy.ndarray

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.shape

(2, 3)

In [18]:
b = np.eye(3, dtype='int8')
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [19]:
b.shape

(3, 3)

In [23]:
c = np.ones((3, 3), dtype='int8')
c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [24]:
d = np.array([
    [
        [1,2], [3,4]
    ],
    [
        [5,6], [7,8]
    ],
    [
        [9,10], [11,12]
    ]
])
d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [25]:
type(d)

numpy.ndarray

In [26]:
e = np.array([
    [
        [1,2,3],
    ],
    [
        [1, 2, 3, 4, 5]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 1) + inhomogeneous part.

In [44]:
f = np.arange(1,12,2, dtype=float).reshape(2, 3)
f

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.]])

In [51]:
g = np.linspace(0, 10, 5, dtype=float)
g

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [55]:
g * 4

array([ 0., 10., 20., 30., 40.])

In [74]:
h = np.random.rand(3)
h

array([0.94815312, 0.94183912, 0.11923094])

In [75]:
h.ndim

1

In [76]:
f.ndim

2

In [84]:
i = np.arange(1,5, dtype=int).reshape(2,2)
ones = np.ones((2,2))
l = np.array(i + ones, dtype=int)
l

array([[2, 3],
       [4, 5]])

In [85]:
i * ones

array([[1., 2.],
       [3., 4.]])

In [86]:
i@ones

array([[3., 3.],
       [7., 7.]])

In [93]:
p = int(i.max())
p

4

In [94]:
i.sum()

np.int64(10)

In [114]:
i = np.array([[1, 2],
       [4, 3],
       [5, 6]])
i

array([[1, 2],
       [4, 3],
       [5, 6]])

In [116]:
i.max(axis=1)

array([2, 4, 6])

In [117]:
i[0][1]

np.int64(2)