In [2]:
import numpy as np

Task 1. Write a Python function that converts a temperature from Fahrenheit to Celsius. Use `numpy.vectorize` to apply this function to an array of temperatures: `[32, 68, 100, 212, 77]`. 
   - Formula: $C = (F - 32) \times \frac{5}{9}$

In [5]:
def f_to_c(f):
    return (f - 32) * 5 / 9

temps = np.array([32, 68, 100, 212, 77])
vectorized_vec = np.vectorize(f_to_c)
celsius_temps = vectorized_vec(temps)
celsius_temps

array([  0.        ,  20.        ,  37.77777778, 100.        ,
        25.        ])

Task 2. Create a custom function that takes two arguments: a number and a power. Use numpy.vectorize to calculate the power for each pair of numbers in two arrays: [2, 3, 4, 5] and [1, 2, 3, 4].

In [4]:
def power_of_vec(n, p):
    return n ** p

vec = np.array([2, 3, 4, 5])
pow = np.array([1, 2, 3, 4])

vectorized_power = np.vectorize(power_of_vec)
vectorized_power(vec, pow)

array([  2,   9,  64, 625])

Task 3. Solve the system of equations using `numpy`:

$$
\begin{cases}
4x + 5y + 6z = 7 \\
3x - y + z = 4 \\
2x + y - 2z = 5
\end{cases}
$$

In [3]:
W = np.array([
    [4,3,2],
    [5,-1,1],
    [6,1,-2]
])

Y = np.array([7,4,5])
ans = np.linalg.solve(W,Y)
ans

array([0.86486486, 0.83783784, 0.51351351])

Task 4. Given the electrical circuit equations below, solve for $I_1, I_2, I_3$ (currenst in the branches)

$$
\begin{cases}
10I_1 - 2I_2 + 3I_3 = 12\\
-2I_1 + 8I_2 - I_3 = -5\\
3I_1 - I_2 + 6I_3 =15
\end{cases}
$$

In [4]:
W = np.array([
    [10, -2, 3],
    [-2, 8, -1],
    [3, -1, 6]
])

Y = np.array([12, -5, 15])

ans = np.linalg.solve(W, Y)
ans

array([ 0.48963731, -0.2253886 ,  2.21761658])

In [30]:
from PIL import Image

with Image.open("images/birds.jpg") as img:
    img_arr = np.array(img)

gray_img_arr = (img_arr[:, :, 0] * 0.299 + img_arr[:, :, 1] * 0.587 + img_arr[:, :, 2] * 0.114).astype(np.int8)

gray_img_arr.shape

(720, 720)

**Image Manipulation with NumPy and PIL**

Image file: `images/birds.jpg`. Your task is to perform the following image manipulations using the **NumPy** library while leveraging **PIL** for reading and saving the image.

**Instructions:**

1. **Flip the Image**:
   - Flip the image horizontally and vertically (left-to-right and up-to-down).

2. **Add Random Noise**:
   - Add random noise to the image.

3. **Brighten Channels**:
   - Increase the brightness of the channels (r.g. red channel) by a fixed value (e.g., 40). Clip the values to ensure they stay within the 0 to 255 range.

4. **Apply a Mask**:
   - Mask a rectangular region in the image (e.g., a 100x100 area in the center) by setting all pixel values in this region to black (0, 0, 0).

**Requirements:**
- Use the **PIL** module onyl to:
  - Read the image.
  - Convert numpy array to image.
  - Save the modified image back to a file.
- Perform all manipulations using NumPy functions. Avoid using image editing functions from PIL or other libraries.


**Bonus Challenge**:
- Create a function for each manipulation (e.g., `flip_image`, `add_noise`, `brighten_channels`, `apply_mask`) to promote modularity and reusability of code.

--- 

In [3]:
from PIL import Image

def flip_image(img_arr):
    # Flip horizontally
    flipped_horizontally = np.fliplr(img_arr)
    # Flip vertically
    flipped_vertically = np.flipud(img_arr)
    return flipped_horizontally, flipped_vertically

def add_noise(img_arr, noise_level=20):
    noise = np.random.randint(-noise_level, noise_level, img_arr.shape, dtype=np.int16)
    noisy_img = img_arr.astype(np.int16) + noise
    noisy_img = np.clip(noisy_img, 0, 255).astype(np.uint8)
    return noisy_img

def brighten_channels(img_arr, brightness_increase=40):
    brightened_img = img_arr.astype(np.int16) + brightness_increase
    brightened_img = np.clip(brightened_img, 0, 255).astype(np.uint8)
    return brightened_img

def apply_mask(img_arr, mask_size=(100, 100)):
    center_x, center_y = img_arr.shape[1] // 2, img_arr.shape[0] // 2
    half_mask_width, half_mask_height = mask_size[0] // 2, mask_size[1] // 2
    masked_img = img_arr.copy()
    masked_img[center_y - half_mask_height:center_y + half_mask_height,
               center_x - half_mask_width:center_x + half_mask_width] = 0
    return masked_img

with Image.open("images/birds.jpg") as img:
    img_arr = np.array(img)


flipped_horizontally, flipped_vertically = flip_image(img_arr)
noisy_img = add_noise(img_arr)
brightened_img = brighten_channels(img_arr)
masked_img = apply_mask(img_arr)

# Save the manipulated images
Image.fromarray(flipped_horizontally).save("images/birds_flipped_horizontally.jpg")
Image.fromarray(flipped_vertically).save("images/birds_flipped_vertically.jpg")
Image.fromarray(noisy_img).save("images/birds_noisy.jpg")
Image.fromarray(brightened_img).save("images/birds_brightened.jpg")
Image.fromarray(masked_img).save("images/birds_masked.jpg")